GET https://api.twitter.com/1.1/search/tweets.json?q=flatearthsociety&response_type=popluar
Authorization: Bearer AAAAAAAAAAAAAAAAAAAAAJ08NgEAAAAAtpHIGiyzu4xBnkFGoI6Hds87TrU%3DL91MtF2VKTSd69dLRQeseT5TRlKNjsV2qL21QyJHoZkANun4y9
