name: Backend Test CD

on:
  push:
    paths:
    - 'bubblemeter/backend/flask_backend/**'

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

     #This Action Emits 2 Variables, IMAGE_SHA_NAME and IMAGE_URL 
     #which you can reference in subsequent steps
    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'flask-backend'
        TAG: 'bubblemeter-backend'
        DOCKERFILE_PATH: 'bubblemeter/backend/flask_backend/Dockerfile'
        BUILD_CONTEXT: '/app'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
